- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"

- name: Install aur packages
  become: true
  become_user: aur_builder
  aur:
    use: paru
    extra_args: --noprovides
    name:
      - curl
      - file
      - libxcrypt-compat
      - procps-ng
      - sccache

      # gui
      - discord
      - kitty

      # Gaming
      - steam
      - wine

      # utils
      - brightnessctl
      - clipman
      - playerctl
      - lm_sensors

      # cli
      - aria2
      - as-tree
      - aspell
      - bat
      - bandwhich
      - bottom
      - broot
      - cava
      - ctop
      - curl
      - direnv
      - duf
      - dust
      - exa
      - fd
      - fnm
      - fzf
      - fzy
      - git
      - git-delta
      - git-lfs
      - github-cli
      # - glow
      - gnupg
      - gnuplot
      - grc
      - htop
      - httpie
      - hub
      - hyperfine
      - jq
      - keychain
      # - languagetool
      - lazydocker
      - lazygit
      - mdcat
      - neofetch
      - neovim-git
      - nodejs-markdownlint-cli
      - nnn
      - nodejs
      - ncdu
      - osmium-tool
      - pass
      - pfetch
      - procs
      - qemu
      - ranger
      - ripgrep
      - rsync
      - selene-git
      - shellcheck
      - shfmt
      - spotify
      - starship
      - stylua
      - tealdeer
      - tmux
      # - tmuxinator
      - tokei
      - wget
      - zsh
      - zoxide
