- name: Create ~/.config
  file:
    path: ~/.config
    state: directory

- name: Find .config files
  find:
    paths: ~/dotfiles/config/
    recurse: no
    file_type: any
    hidden: yes
  register: dot_config

- name: ~/.config/
  file:
    src: "{{item.path}}"
    dest: "~/.config/{{item.path | basename}}"
    state: link
  loop: "{{ dot_config.files }}"
  loop_control:
    label: "~/.config/{{item.path | basename}}"

- name: .zshrc
  file:
    src: ~/.config/.zshrc
    dest: ~/.zshrc
    state: link

- name: .gitconfig
  file:
    src: ~/.config/.gitconfig
    dest: ~/.gitconfig
    state: link

- name: .imwheelrc
  file:
    src: ~/.config/.imwheelrc
    dest: ~/.imwheelrc
    state: link

- name: .ssh/config
  copy:
    src: ~/.config/.ssh.config
    dest: ~/.ssh/config
    mode: u=rw,o=,g=

- name: .ssh/config/control
  file:
    path: ~/.ssh/control
    state: directory
    mode: u=rwx,o=,g=

- name: gpg-agent.conf
  copy:
    dest: ~/.gnupg/gpg-agent.conf
    content: "pinentry-program /bin/pinentry"
