#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

for i in {1..3}; do
    space=$(yabai -m query --spaces --space "$i")
    if [ -z "$space" ]; then
		echo "Creating space $i"
        yabai -m space --create
    fi
done

yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label media

yabai -m rule --add app="^Thorium$" space=web
yabai -m rule --add app="^Ghostty$" space=code
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^Slack$"   space=media
yabai -m rule --add app="^Element$" space=media
yabai -m rule --add app="^(Docker Desktop|System Settings|Activity Monitor|Installer|Finder)$" manage=off
yabai -m rule --add app="^IINA$" manage=off sticky=on grid=8:8:6:0:2:2

yabai -m signal --add event=window_created app="^Ghostty$" action="yabai -m window --focus $YABAI_WINDOW_ID"

# Ensure focus stays in code space when new Ghostty windows appear
yabai -m signal --add event=window_created app="^Ghostty$" \
    action="yabai -m space --focus code"

borders "active_color=gradient(top_left=0xff9ccfd8,bottom_right=0xff31748f) inactive_color=0xff6e6a86 width=5.0 &"

gap=10
yabai -m config                                 \
    mouse_follows_focus       off               \
    focus_follows_mouse       off               \
    window_placement          second_child      \
    window_shadow             on                \
    window_animation_duration 0.25              \
    insert_feedback_color     0xff9dd274        \
    split_ratio               0.50              \
    split_type                auto              \
    auto_balance              off               \
    top_padding               $gap              \
    left_padding              $gap              \
    right_padding             $gap              \
    bottom_padding            $gap              \
    window_gap                $gap              \
    layout                    bsp               \
    mouse_modifier            fn                \
    mouse_action1             move              \
    mouse_action2             resize            \
    mouse_drop_action         swap              \

yabai -m space code --layout stack

echo "yabai configuration loaded.."
